<?php
$survey_question_Status = Mage::getStoreConfig('grizzly_ordersocial/social/enable_social',Mage::app()->getStore());

$survey_question = Mage::getStoreConfig('grizzly_ordersocial/social/survey_question',Mage::app()->getStore());
?>
<form action="" id="checkout-agreements" onsubmit="return false;">
    <?php if($survey_question_Status && isset($survey_question_Status)) { ?>
    <div class="buttons-set">
        <ul class="form-list">
            <li>
                <fieldset>
                    <ul>
                        <li>
                            <label class="commentlabel" for="ordercomment-comment">
                            <?php echo $survey_question; ?></label>
                            <div>
                                <input type="text" id="socialtype" class="input-text validation-passed" name="socialtype" title="<?php echo $survey_question ?>"></input>
                            </div>
                        </li>
                        
                    </ul>
                </fieldset>
            </li>
        </ul>
    </div>
    <?php } ?>
    <?php if ($this->getAgreements()): ?>
        <ol class="checkout-agreements">
            <?php foreach ($this->getAgreements() as $_a): ?>
            <li>
                <div class="agreement-content"<?php echo ($_a->getContentHeight() ? ' style="height:' . $_a->getContentHeight() . '"' : '')?>>
                    <?php if ($_a->getIsHtml()):?>
                    <?php echo $_a->getContent() ?>
                    <?php else:?>
                    <?php echo nl2br($this->htmlEscape($_a->getContent())) ?>
                    <?php endif; ?>
                </div>
                <p class="agree">
                    <input type="checkbox" id="agreement-<?php echo $_a->getId()?>" name="agreement[<?php echo $_a->getId()?>]" value="1" title="<?php echo $this->htmlEscape($_a->getCheckboxText()) ?>" class="checkbox" /><label for="agreement-<?php echo $_a->getId()?>"><?php echo $_a->getIsHtml() ? $_a->getCheckboxText() : $this->htmlEscape($_a->getCheckboxText()) ?></label>
                </p>
            </li>
            <?php endforeach ?>
        </ol>
    <?php endif; ?>
</form>


<!--<script type="text/javascript">
    // Add our field to the data submitted by Review.save()
    Review.prototype.save = Review.prototype.save.wrap(function(orig) {
        var form = this.agreementsForm ? this.agreementsForm : payment.form;
        if (form) {
            var myfield = $('socialtype');
            form.insert(myfield);
        }
        orig();
    });
</script>-->