<?php if ($this->isActive()):
    ?><script>var EnableOptOut = false;</script>
    <?php
        
        if($this->isUserOptOutEnable()):
            ?><script>EnableOptOut = true;</script><?php
        endif;
        ?>


    <script type="text/javascript">

        if(EnableOptOut){
               // Set to the same value as the web property used on the site
               var gaProperty = '<?php echo $this->getAccountId(); ?>';
       
               // Disable tracking if the opt-out cookie exists.
               var disableStr = "ga-disable-" + gaProperty;
               if (document.cookie.indexOf(disableStr + "=true") > -1) {
                 window[disableStr] = true;
               }
       
               // Opt-out function
               function gaOptout() {
               var expDate = new Date;
               expDate.setMonth(expDate.getMonth() + 26);
                 document.cookie = disableStr + "=true; expires="+expDate.toGMTString();+"path=/";
                 window[disableStr] = true;
               }
        }
    </script> 

        <!-- Google Tag Manager -->
        <noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-PZPBCH"
                          height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
        <script>(function(w, d, s, l, i) {
                w[l] = w[l] || [];
                w[l].push({'gtm.start':
                            new Date().getTime(), event: 'gtm.js'});
                var f = d.getElementsByTagName(s)[0],
                        j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
                j.async = true;
                j.src =
                        '//www.googletagmanager.com/gtm.js?id=' + i + dl;
                f.parentNode.insertBefore(j, f);
            })(window, document, 'script', 'dataLayer', 'GTM-PZPBCH');

        </script> 
        <!-- End Google Tag Manager -->
    <script type="text/javascript">

        (function(i, s, o, g, r, a, m) {
            i["GoogleAnalyticsObject"] = r;
            i[r] = i[r] || function() {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                    m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, "script", "//www.google-analytics.com/analytics.js", "ga");

        ga('create', '<?php echo $this->getAccountId(); ?>', '<?php echo $this->getRequest()->getHttpHost() ?>');
	   <?php if($this->isAnon()){ ?>
ga('set', 'anonymizeIp', true);
        <?php } ?>

        ga("require", "ec", "ec.js");
    <?php
    if ($this->getBrandAttr() != '') {
        $brand_code = $this->getBrandAttr();
    } else {
        $brand_code = '';
    }

    function t_getBrandValue($product, $t_brand_code) {

        if (isset($t_brand_code)) {

            $t_brand = $product->getResource()->getAttribute($t_brand_code);
            if ($t_brand) {
                return addslashes(trim($t_brand->getFrontend()->getValue($product)));
            } else {
                return '';
            }
        } else {
            return '';
        }
    }
    
    $brandAtt = $this->getBrandAttr();

    if ($brandAtt == "") {
        $brandAtt = "";
        $getProductBrand = 'getBrand';
    }
    else
        $getProductBrand = 'get' . strtolower($brandAtt);
    ?>

    <?php if ($this->isEcommerce()): ?>

        <?php

        $_order = Mage::getSingleton('sales/order')->load(Mage::getSingleton('checkout/session')->getLastOrderId());
        $order = Mage::getSingleton('sales/order')->load($_order->getData($this->getTransactionIdField()));
        $items = $order->getAllItems();
        $data = array();
        $i = 0;

        ?>

        ga('set', '&cu', '<?php echo $_order->getOrderCurrencyCode(); ?>');
        var orderObject = {};

        <?php
        $catIds = "";
        foreach ($items as $itemId => $item) {
            $cats = $item->getProduct()->getCategoryIds();
            foreach ($cats as $category_id) {
                $_cat = Mage::getSingleton('catalog/category')->load($category_id);
                $catIds.=$_cat->getName() . ",";
            }
            $product_sku = $item->getSku();
            if ($product_sku == ""):
                $product_sku = $item->getId();
            endif;

            $productId = $item->getProduct()->getId();
            $_product = Mage::getSingleton('catalog/product')->load($productId);
            ?>

            orderObject['<?php echo $i ?>'] = {
                'sku': '<?php echo addslashes($product_sku); ?>',
                'Name': '<?php echo addslashes($item->getName()); ?>',
                'Price': '<?php echo $item->getProduct()->getFinalPrice(); ?>',
                'qty': '<?php echo $item->getQtyToInvoice(); ?>',
                'qty1': '<?php echo intVal($item->getQtyOrdered()); ?>',
                'categories': '<?php echo addslashes(trim($catIds, ",")); ?>',
                'brand': '<?php echo addslashes(t_getBrandValue($_product, $brand_code)) ?>'
            }

            <?php
                $catIds = "";
                $data[$i]['name'] = $item->getName();
                $data[$i]['price'] = $item->getProduct()->getFinalPrice();
                $data[$i]['sku'] = $item->getSku();
                $data[$i]['id'] = $item->getProductId();
                $data[$i]['qty1'] = $item->getQtyToInvoice();
                $data[$i]['brand'] = $item->getProduct()->$getProductBrand();
            $i++;
        }
        $catIds = "";
        ?>
                    transactionObject = {};
                    transactionObject = {
                        'tid': '<?php echo $_order->getIncrementId(); ?>',
                        'aid': '<?php echo addslashes(Mage::app()->getStore()->getName()) ?>',
                        'revenue': '<?php echo $_order->getGrandTotal() ?>',
                        'tax': '<?php echo $_order->getTaxAmount() ?>',
                        'shipping': '<?php echo $_order->getShippingInclTax() ?>',
                        'ccode': '<?php echo addslashes($_order->getCouponCode()); ?>'
                    }
                    
                    for (orderItem in orderObject) {
                        ga('ec:addProduct', {
                            'id': orderObject[orderItem]['sku'],
                            'name': orderObject[orderItem]['Name'],
                            'category': orderObject[orderItem]['categories'],
                            'brand': orderObject[orderItem]['brand'],
                            'price': orderObject[orderItem]['Price'],
                            'quantity': orderObject[orderItem]['qty1']
                        });
                    }

                    ga('ec:setAction', 'purchase', {
                        'id': transactionObject['tid'],
                        'affiliation': transactionObject['aid'],
                        'revenue': transactionObject['revenue'],
                        'tax': transactionObject['tax'],
                        'shipping': transactionObject['shipping'],
                        'coupon': transactionObject['ccode']    // User added a coupon at checkout.
                    });

                    // ga("send", "event", "Enhanced-Ecommerce", "load", "order_confirmation", {"nonInteraction": 1});
        
        <?php endif; ?>

        ga('send', 'pageview');
    </script>
<?php endif; ?>