<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2015 Amasty (https://www.amasty.com)
 * @package Amasty_Orderattr
 */

$attributes = $this->getAttributes();
?>
<?php if (!empty($attributes)): ?>
    <div class="col-1">
        <div class="box" id="amorderattr-block">
            <div class="box-title">
                <h2><?php echo $this->__('Additional Info'); ?></h2>
            </div>
            <div class="box-content">
                <table border="0">
                    <tbody>
                        <?php foreach ($attributes as $label => $value): ?>
                        <tr>
                            <td style="padding-left: 0;">
                                <?php echo $label; ?>:
                            </td>
                            <td style="padding-left: 0;">
                                <?php echo nl2br(htmlentities(preg_replace('/\$/','\\\$', $value), ENT_COMPAT, "UTF-8")); ?>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
<?php endif; ?>