<style media="screen" type="text/css">
.freecontactform {
width: 460px;
font-family: arial;
border: 1px solid #AAA;
padding:10px;
-moz-border-radius: 10px;
-webkit-border-radius: 10px;
border-radius: 10px;
}
.freecontactformheader {
font-size:18px;
font-weight:bold;
padding-top:10px;
padding-bottom:10px;
text-align:left;
}
.freecontactformmessage {
text-align:left;
padding-bottom:10px;
}
.freecontactform td {
padding:4px;
font-size:12px;
}
.freecontactform p {
padding:4px;
}
.freecontactform label {
padding:4px;
}
.freecontactform label {
padding-right:10px
}
.required {
font-weight:bold;
}
.required_star {
font-weight:bold;
color:#F00;
}
.not-required {
font-weight:normal
}
.antispammessage {
padding:10px;
border-top:1px solid #AAA;
border-bottom:1px solid #AAA;
font-weight:bold 
}
.antispamquestion {
font-weight:normal;
}
</style>
<?php 
$Full_Name = $_POST['Full_Name'];
$Email_Address = $_POST['Email_Address'];
$Telephone_Number = $_POST['Telephone_Number'];
$Your_Message = $_REQUEST['Your_Message'];
$AntiSpam = $_POST['AntiSpam'];
$Institution = $_POST['Institution'];


if(isset($_POST['Submit']))
{
	if ($AntiSpam == '25')
	{
		$to = "TechSupport@sciencellonline.com";
		$subject = "CONTACT FORM";
		$from = $Email_Address;
		$message = "From: $Full_Name \n E-Mail: $Email_Address \n\n Name of the Institution: $Institution \n\n Message: $Your_Message";
		$headers = "From: $from \r\n";
		$headers .= "Reply-To: $from \r\n";
		$headers .= "Return-Path: $from \r\n";
		$headers .= "X-Mailer: PHP \r\n";
		
		if(mail($to,$subject,$message,$headers)) 
		{
			echo "<br /><div align=\"left\"><b><span>We appreciate your interest in ScienCell products, One of us will get right back to you!</span></b></div><br />";
		}
		else
			echo "Not Sent!";
	}
	else
		echo "The Antispam answer you provided is wrong, please try again";
}
else
{
	echo $AntiSpam;
?>	
<form name="freecontactform" method="post" action="https://www.sciencellonline.com/contact-us.html" onsubmit="return validate.check(this)"> 
    <table style="width:100%; height:100%" border="0" cellpadding="15" cellspacing="10">
  <tr>
    <td style="padding:10px" colspan="4" align="left">	 
    <div class="freecontactformheader"><font style="font-size:16px; font-weight:bold">Customer Information:</font></div>
	  
	 <div class="freecontactformmessage">Fields marked with <span class="required_star"> * </span> are mandatory.</div>
     </td>
    </tr>
  <tr>
    <td style="padding:10px" width="102"> <label for="Full_Name" class="required">Full Name<span class="required_star"> * </span></label></td>
    <td style="padding:10px" width="230"><input width="40"   type="text" name="Full_Name" id="Full_Name" maxlength="80" style="width:230px" required></td>
  
    
  </tr>
  <tr>
    <td style="padding:10px"><label for="Email_Address2" class="required">Email Address<span class="required_star"> * </span></label></td>
    <td style="padding:10px"><input width="40"   type="email" name="Email_Address" id="Email_Address" maxlength="100" style="width:230px" required></td>
    </tr>
  <tr>
    <td style="padding:10px"><label for="Telephone_Number2" class="not-required">Telephone Number</label></td>
    <td style="padding:10px"><input width="40"   type="text" name="Telephone_Number" id="Telephone_Number" maxlength="100" style="width:230px"></td>
    </tr>
    <tr>
    	<td style="padding:10px"><label for="Institution" class="required">   	  Name of your Institution? <span class="required_star">* </span></label></td>
   	  <td style="padding:10px"><input width="40"   type="text" name="Institution" id="Institution" maxlength="100" style="width:230px" />
   	  </td>
         
    </tr>
    
  <tr>
    <td style="padding:10px" colspan="4" width="123" valign="top"><p><span class="required">Your Message? <span class="required_star">* </span></span></p>
</tr>
  <tr>
   <td style="padding:10px"  colspan="4"><textarea style="width:450px; height:100px" name="Your_Message" id="Your_Message" maxlength="2000" required></textarea></td>
    </tr>
  <tr>
    <td colspan="3" rowspan="-1" align="center">To help prevent automated spam, please answer this question <br />
      <br />
      <div class="antispamquestion">Using only numbers, what is 10 plus 15?<span class="required_star"> * </span> &nbsp;
        <input width="40"   type="text" name="AntiSpam" id="AntiSpam" maxlength="100" style="width:60px" required>
    </div>&nbsp;</td>
  </tr>
  <tr>
    <td colspan="4"><center>
      <input width="40"   type="submit" name="Submit" value=" Submit Form " style="width:200px;height:40px; color:#F00;">
      </center>&nbsp;</td>
  </tr>

</table>
</form>
<?php
}
?>