<?php /** 
* Moogento
* 
* SOFTWARE LICENSE
* 
* This source file is covered by the Moogento End User License Agreement
* that is bundled with this extension in the file License.html
* It is also available online here:
* https://moogento.com/License.html
* 
* NOTICE
* 
* If you customize this file please remember that it will be overwritten
* with any future upgrade installs. 
* If you'd like to add a feature which is not in this software, get in touch
* at moogento.com for a quote.
* 
* ID          pe+sMEDTrtCzNq3pehW9DJ0lnYtgqva4i4Z=
* File        nomorespam_review.phtml
* @category   Moogento
* @package    noMoreSpam
* @copyright  Copyright (c) 2017 Moogento <info@moogento.com> / All rights reserved.
* @license    https://moogento.com/License.html
*/ ?>
<div id="<?php echo Mage::helper("nomorespam")->getNmsId();?>">
    <input type="text" name="<?php echo Mage::helper("nomorespam")->getNmsField1();?>" id="<?php echo Mage::helper("nomorespam")->getNmsField1()?>" value="<?php echo Mage::helper("nomorespam")->createValue(); ?>" style="display:none !important;" />
    <input type="hidden" name="<?php echo Mage::helper("nomorespam")->getNmsField2();?>" id="<?php echo Mage::helper("nomorespam")->getNmsField2();?>" value="" />
	<?php if(Mage::helper("nomorespam")->IsToofast() == 1):?>
		<input type="hidden" id="<?php echo Mage::helper("nomorespam")->getNmsTooFast();?>" name="<?php echo Mage::helper("nomorespam")->getNmsTooFast();?>" value="<?php echo microtime(true) ?>" />
	<?php endif;?>	
</div>
<script type="text/javascript">
Element.addMethods({getText:function(element){a=$(element);return a.innerHTML;}});$(document).on('dom:loaded',function(){var b="<?php echo Mage::helper("nomorespam")->getNmsId();?>";var c=$(b).getText();if(c){$('newsletter-validate-detail').insert({top:c});$(b).remove();}});
</script>